### PR TITLE
Update to 5.70.0

### PR DESCRIPTION
**Pull request by jbruechert**
Pretty much just a merge from debian. I'm probably way beyond the feature freeze for the next ota again, but it would still have advantages for me if a newer kirigami version is at least available in the repository.

Background: Users are asking for a new Kaidan build for Ubuntu Touch now that Qt 5.12 appears to arrive in UT soon.

### CODE REVIEW

**Comment by Flohack74** [comment]
Yeah Im afraid we can only merge it after OTA-13, but 14 should be faster this time ^^

**Comment by jbruechert** [comment]
Depends on https://github.com/ubports/extra-cmake-modules-packaging/pull/4

**Comment by mariogrip** [comment]
Thank you! :)

WIll put this on for OTA-14 (next release) as we are currently in freeze :)

Will this work without qt 5.12 merged first?

**Comment by jbruechert** [comment]
No, unfortunately this will need Qt 5.12. I haven't followed the recent progress that closely, so I wasn't sure whether the Qt update is already in the repository or not.

**Comment by dobey** [comment]
As this requires Qt 5.12, and given how we're changing how related packaging branches are managed with the Qt 5.12 upgrade, I'm going to close this. Instead, I'll make the appropriate repo on GitLab (where we've migrated some packaging repos, based off the upstream debian/ubuntu git repos workflow), based on the upstream debian repo, with the branch for the 5.12 upgrade, so it can be tested along with the update. Thanks!

**Pull request closed without merging**
